export type FormData = {
  name: string;
  userId: string;
  genre: string;
  location: string;
  birthday: string;
  image: string;
  writing: string;
  twitterUrl: string;
  instagramUrl: string;
  homepageUrl: String;
  otherUrl: String;
  eventName: string;
  eventLocation: string;
  eventDate: string;
  openTime: string;
  closeTime: string;
  minAmount: string;
  maxAmount: string;
  coupon: string;
  tickets: string;
  search: string;
};
