import 'tailwindcss/tailwind.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { RecoilRoot } from 'recoil';
import 'instantsearch.css/themes/satellite-min.css';
import '../../src/styles/algolia.css';
import { DefaultSeo } from 'next-seo';
import { Toaster } from 'react-hot-toast';
import { SEO } from '../../next-seo.config';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DefaultSeo {...SEO} />

      <RecoilRoot>
        <Component {...pageProps} />
        <Toaster />
      </RecoilRoot>
    </>
  );
}
export default MyApp;
