import 'tailwindcss/tailwind.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { RecoilRoot } from 'recoil';
import 'instantsearch.css/themes/satellite-min.css';
import '../../src/styles/algolia.css';
import { DefaultSeo, NextSeo } from 'next-seo';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <DefaultSeo
        defaultTitle="Seartist"
        canonical="https://seartist.vercel.app/"
        description="Seartistは、アーティストや主催者がイベント情報を告知し、沢山の方々にをイベント情報を知ってもらう為のアプリです。"
        twitter={{
          handle: '@watajamsan',
          site: '@watajamsan',
          cardType: 'summary',
        }}
        openGraph={{
          type: 'website',
          title: 'Seartist',
          description:
            'Seartistは、アーティストや主催者がイベント情報を告知し、沢山の方々にをイベント情報を知ってもらう為のアプリです。',
          site_name: 'Seartist',
          url: 'https://seartist.vercel.app/',
          // TODO OGP画像
          images: [
            {
              url: 'https://light.dotup.org/uploda/light.dotup.org14180.png_ngKbwCYY3GZDZA6qNGPh/light.dotup.org14180.png',
              width: 800,
              height: 600,
              alt: 'Seartist',
            },
          ],
        }}
      />
      <Head>
        {/* <title>Seartist</title> */}
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <RecoilRoot>
        <Component {...pageProps} />
      </RecoilRoot>
    </>
  );
}
export default MyApp;
