import "tailwindcss/tailwind.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Seartist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="red" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
